### ISSUE TITLE
Home - Hero section

### ISSUE THREAD

**Issue by danielgeen** [markendley/jde#2]
1. Please put a slight drop shadow on all page titles in the hero section. 
2. Could the button in the home page hero section please be the turquoise colour with white outline?
3. Can the button animate in just after the title? instead of all coming in at once. 
4. On mobile and tablet please put a 20% black overlay over the image so the writing is more legible?

**Comment by markendley** [comment]
done

**Comment by danielgeen** [comment]
Thanks but could you please reduce the opacity of the shadow a bit and make a little more subtle...

**Comment by markendley** [comment]
not subtle enough?

I just changed the opacity from 70% down to 40%

**Comment by danielgeen** [comment]
Perfect thanks!
